// Extended list for autocomplete — symbol + name + sector
export interface StockSuggestion {
  symbol: string
  name: string
  sector: string
}

export const AUTOCOMPLETE_EXTRA: StockSuggestion[] = [
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Financials' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology' },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology' },
  { symbol: 'ACN', name: 'Accenture plc', sector: 'Technology' },
  { symbol: 'MCD', name: "McDonald's Corporation", sector: 'Consumer Discretionary' },
  { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer Staples' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Staples' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare' },
  { symbol: 'NKE', name: 'Nike Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'LOW', name: "Lowe's Companies Inc.", sector: 'Consumer Discretionary' },
  { symbol: 'HD', name: 'The Home Depot Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer Staples' },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'BAC', name: 'Bank of America Corp.', sector: 'Financials' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', sector: 'Financials' },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financials' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Financials' },
  { symbol: 'AXP', name: 'American Express Company', sector: 'Financials' },
  { symbol: 'SCHW', name: 'Charles Schwab Corp.', sector: 'Financials' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Financials' },
  { symbol: 'MCO', name: "Moody's Corporation", sector: 'Financials' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', sector: 'Healthcare' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Healthcare' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', sector: 'Healthcare' },
  { symbol: 'SYK', name: 'Stryker Corporation', sector: 'Healthcare' },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'Healthcare' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrials' },
  { symbol: 'HON', name: 'Honeywell International', sector: 'Industrials' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrials' },
  { symbol: 'LMT', name: 'Lockheed Martin Corp.', sector: 'Industrials' },
  { symbol: 'NOC', name: 'Northrop Grumman Corp.', sector: 'Industrials' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrials' },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrials' },
  { symbol: 'FDX', name: 'FedEx Corporation', sector: 'Industrials' },
  { symbol: 'F', name: 'Ford Motor Company', sector: 'Consumer Discretionary' },
  { symbol: 'GM', name: 'General Motors Company', sector: 'Consumer Discretionary' },
  { symbol: 'LCID', name: 'Lucid Group Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NKLA', name: 'Nikola Corporation', sector: 'Consumer Discretionary' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', sector: 'Technology' },
  { symbol: 'MU', name: 'Micron Technology Inc.', sector: 'Technology' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', sector: 'Technology' },
  { symbol: 'LRCX', name: 'Lam Research Corp.', sector: 'Technology' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Technology' },
  { symbol: 'ASML', name: 'ASML Holding N.V.', sector: 'Technology' },
  { symbol: 'IBM', name: 'IBM Corporation', sector: 'Technology' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Technology' },
  { symbol: 'DELL', name: 'Dell Technologies Inc.', sector: 'Technology' },
  { symbol: 'ZM', name: 'Zoom Video Communications', sector: 'Technology' },
  { symbol: 'OKTA', name: 'Okta Inc.', sector: 'Technology' },
  { symbol: 'DDOG', name: 'Datadog Inc.', sector: 'Technology' },
  { symbol: 'MDB', name: 'MongoDB Inc.', sector: 'Technology' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Technology' },
  { symbol: 'WDAY', name: 'Workday Inc.', sector: 'Technology' },
  { symbol: 'HUBS', name: 'HubSpot Inc.', sector: 'Technology' },
  { symbol: 'TWLO', name: 'Twilio Inc.', sector: 'Technology' },
  { symbol: 'RBLX', name: 'Roblox Corporation', sector: 'Technology' },
  { symbol: 'U', name: 'Unity Software Inc.', sector: 'Technology' },
  { symbol: 'SNAP', name: 'Snap Inc.', sector: 'Communication Services' },
  { symbol: 'PINS', name: 'Pinterest Inc.', sector: 'Communication Services' },
  { symbol: 'RDDT', name: 'Reddit Inc.', sector: 'Communication Services' },
  { symbol: 'LYFT', name: 'Lyft Inc.', sector: 'Technology' },
  { symbol: 'DASH', name: 'DoorDash Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'EXPE', name: 'Expedia Group Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc.', sector: 'Financials' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Financials' },
  { symbol: 'CME', name: 'CME Group Inc.', sector: 'Financials' },
  { symbol: 'SQ', name: 'Block Inc.', sector: 'Financials' },
  { symbol: 'AFRM', name: 'Affirm Holdings Inc.', sector: 'Financials' },
  { symbol: 'UPST', name: 'Upstart Holdings Inc.', sector: 'Financials' },
  { symbol: 'AMT', name: 'American Tower Corp.', sector: 'Real Estate' },
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate' },
  { symbol: 'EQIX', name: 'Equinix Inc.', sector: 'Real Estate' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.', sector: 'Utilities' },
  { symbol: 'DUK', name: 'Duke Energy Corporation', sector: 'Utilities' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities' },
  { symbol: 'VZ', name: 'Verizon Communications', sector: 'Communication Services' },
  { symbol: 'T', name: 'AT&T Inc.', sector: 'Communication Services' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', sector: 'Communication Services' },
  { symbol: 'CHTR', name: 'Charter Communications', sector: 'Communication Services' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', sector: 'Communication Services' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health Corporation', sector: 'Healthcare' },
  { symbol: 'CI', name: 'Cigna Group', sector: 'Healthcare' },
  { symbol: 'HUM', name: 'Humana Inc.', sector: 'Healthcare' },
  { symbol: 'ROKU', name: 'Roku Inc.', sector: 'Communication Services' },
  { symbol: 'TTD', name: 'The Trade Desk Inc.', sector: 'Technology' },
  { symbol: 'APP', name: 'AppLovin Corporation', sector: 'Technology' },
  { symbol: 'APLD', name: 'Applied Digital Corp.', sector: 'Technology' },
  { symbol: 'CORZ', name: 'Core Scientific Inc.', sector: 'Technology' },
  { symbol: 'CLSK', name: 'CleanSpark Inc.', sector: 'Technology' },
  { symbol: 'MARA', name: 'MARA Holdings Inc.', sector: 'Technology' },
  { symbol: 'RIOT', name: 'Riot Platforms Inc.', sector: 'Technology' },
  { symbol: 'HUT', name: 'Hut 8 Corp.', sector: 'Technology' },
  { symbol: 'GLD', name: 'SPDR Gold Shares ETF', sector: 'ETF' },
  { symbol: 'SLV', name: 'iShares Silver Trust ETF', sector: 'ETF' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', sector: 'ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', sector: 'ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', sector: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', sector: 'ETF' },
  { symbol: 'SOXL', name: 'Direxion Semiconductor 3x Bull', sector: 'ETF' },
  { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ 3x', sector: 'ETF' },
  { symbol: 'SPXL', name: 'Direxion S&P 500 3x Bull', sector: 'ETF' },
]
